version: '3.3'
services:
  app:
    image: laguzs/gnosis_main_service:1.0
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./certificates:/app/certificates
      - ./resources:/app/resources